nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_private_network: false
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        origin_regex: true
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/api/': null
        '^/': null